In [1]:
import numpy as np

Create a NumPy array called my_scores using np.array() with your last 5 Zomato order ratings (pick any integers between 1 and 5), and print the array.

In [2]:
my_scores = np.array([4.5,3,5,4,2.5])
print(my_scores)

[4.5 3.  5.  4.  2.5]


Use np.arange() to generate an array of all even numbers between 10 and 30 (inclusive), then print the result.

In [3]:
even = np.arange(10,31,2)
print(even)

[10 12 14 16 18 20 22 24 26 28 30]


Generate an array of 8 equally spaced values between 0 and 1 using np.linspace(), and print the array.<br><br><em><strong>Hint:</strong> This is similar to how Spotify creates smooth volume sliders.</em>

In [4]:
values = np.linspace(0,1,8)
print(values)

[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]


Simulate a Flipkart-style 'Add to Cart' button counter by creating a NumPy array of 10 zeros using np.zeros(), then update the 3rd and 7th items to 1 (representing items added to cart), and print the updated array.

In [5]:
add_to_cart = np.zeros(10,dtype = int)
print(add_to_cart)

add_to_cart[2] = 1
add_to_cart[6] = 1
print(add_to_cart)

[0 0 0 0 0 0 0 0 0 0]
[0 0 1 0 0 0 1 0 0 0]


Use np.random.randint() to create an array of 6 random integers between 1000 and 9999 (representing random OTP codes like Paytm), and print the array.<br><br><em><strong>Constraint:</strong> Set the random seed to 42 using np.random.seed(42) before generating the array so your results are reproducible.</em>

In [11]:
np.random.seed(42)

OTP = np.random.randint(1000,10000,size = 6)
print("Otp : ",OTP)

Otp :  [8270 1860 6390 6191 6734 7265]
