In [1]:
import numpy as np

Create two NumPy arrays representing the ratings of 5 restaurants on Zomato and Swiggy, then use np.concatenate() to combine them into a single array of 10 ratings and print the result.

In [6]:
zomato = np.array([3,4,2,5,4])
swiggy = np.array([3,5,3,4,2])

result = np.concatenate((zomato,swiggy))
print('concatenate:',result)

concatenate: [3 4 2 5 4 3 5 3 4 2]



Given three arrays representing the number of likes on three different Instagram posts over 7 days, stack them vertically using np.vstack() so that each row represents one post's weekly likes, and print the stacked array.

In [8]:
post1 = np.array([30,50,32,45,70,63,98])
post2 = np.array([40,42,50,55,32,74,81])
post3 = np.array([80,65,39,48,73,44,59])

result = np.vstack((post1,post2,post3))
print('vstack:----')
print(result)

vstack:----
[[30 50 32 45 70 63 98]
 [40 42 50 55 32 74 81]
 [80 65 39 48 73 44 59]]


You have an array of 12 Flipkart product IDs. Use np.array_split() to divide this array into 5 nearly equal parts, and display each part.<br><br><em><strong>Hint:</strong> Check the shape of each split to confirm the division.</em>

In [14]:
product_id = np.arange(101,113).reshape(12)
print(product_id)

result = np.array_split(product_id,5)
print(result)

[101 102 103 104 105 106 107 108 109 110 111 112]
[array([101, 102, 103]), array([104, 105, 106]), array([107, 108]), array([109, 110]), array([111, 112])]


Simulate a WhatsApp group chat: create a 2D NumPy array where each row is a user and each column is the number of messages sent per day for a week. Use np.insert() to add a new user (row) with their message counts, then use np.delete() to remove the user who sent the least messages overall.

In [69]:
chat = np.array([[10,25,10,8,9,20,9],[7,8,10,20,6,18,17]])
print(chat)

print('Insert:----')
new_user = np.insert(chat,2,[19,15,10,9,20,13,12],axis=0)
print(new_user)

print('Toatl_msg:----')
total_msg = chat.sum(axis=1)
print(total_msg)

print('argmin:----')
least_active_idx = np.argmin(total_msg)
print(least_active_idx)

print('Delete_user:----')
delete_user = np.delete(chat,least_active_idx,axis=0)
print(delete_user)

[[10 25 10  8  9 20  9]
 [ 7  8 10 20  6 18 17]]
Insert:----
[[10 25 10  8  9 20  9]
 [ 7  8 10 20  6 18 17]
 [19 15 10  9 20 13 12]]
Toatl_msg:----
[91 86]
argmin:----
1
Delete_user:----
[[10 25 10  8  9 20  9]]



Given a NumPy array of YouTube video view counts, use .view() to create a view and .copy() to create a copy. Modify the first element in each and print all arrays to demonstrate the difference between view and copy.<br><br><em><strong>Hint:</strong> Observe which changes affect the original array.</em>

In [74]:
view_count = np.array([452,236,789,958,1000,874])

print('copy:----')
a = view_count
a1 = view_count.copy()
a1[0] = 500
print(a)
print(a1)

print('view:----')
b = view_count
b1 = view_count.view()
b1[0] = 500
print(b)
print(b1)

copy:----
[ 452  236  789  958 1000  874]
[ 500  236  789  958 1000  874]
view:----
[ 500  236  789  958 1000  874]
[ 500  236  789  958 1000  874]
