Create a NumPy array representing the number of likes on 7 Instagram posts and print its ndim, shape, size, dtype, itemsize, and nbytes properties.

In [1]:
import numpy as np

In [2]:
instagram_likes = np.array([450,780,620,970,832,1000,745])

print('instagram likes:',instagram_likes)
print('number of dimensions:', instagram_likes.ndim)
print('Shape:', instagram_likes.shape)
print('size:', instagram_likes.size)
print('Data Type:', instagram_likes.dtype)
print('Item-size:', instagram_likes.itemsize)
print('nbytes:', instagram_likes.nbytes)

instagram likes: [ 450  780  620  970  832 1000  745]
number of dimensions: 1
Shape: (7,)
size: 7
Data Type: int64
Item-size: 8
nbytes: 56


Given a 2D NumPy array of daily step counts for 5 days (each row is a day, columns are morning and evening), use reshape() to convert it into a 1D array, then back to a 2D array with 5 rows and 2 columns.<br><br><em><strong>Hint:</strong> Use the shape attribute to check your array after each reshape.</em>

In [19]:
step_counts = np.array([[120,450,330,156,745],[478,126,451,956,785]])

print('1D array:',step_counts.reshape(-1))
print('2D array:',step_counts.reshape(5,2))

1D array: [120 450 330 156 745 478 126 451 956 785]
2D array: [[120 450]
 [330 156]
 [745 478]
 [126 451]
 [956 785]]



Build a NumPy array representing the prices of 12 food items from a Zomato order, then use ravel(), flatten(), and resize() to create different shaped versions of the data and print each result.<br><br><em><strong>Constraint:</strong> Show the difference between ravel() and flatten() in your code comments.</em>

In [36]:
arr = np.array([[50,60,150,80],[65,45,63,52],[41,71,56,96]])
print(arr)
a = arr

#ravel(If we change value in this array it will be changed in original matrix to)
a1 = a.ravel()
print('Ravel:',a1)

#flatten(If we change value in this array it will not be changed in original matrix.)
a2 = a.flatten()
print('Flatten:',a2)

#resize
a3 = np.resize(arr, (2,2))
print('Resize:',a3)

[[ 50  60 150  80]
 [ 65  45  63  52]
 [ 41  71  56  96]]
Ravel: [ 50  60 150  80  65  45  63  52  41  71  56  96]
Flatten: [ 50  60 150  80  65  45  63  52  41  71  56  96]
Resize: [[ 50  60]
 [150  80]]



Take a 3x3 NumPy array representing a mini Spotify playlist grid (rows: playlists, columns: song counts in categories like Pop, Rock, Indie). Use both T and np.transpose() to swap rows and columns, then print the transposed array.

In [32]:
spotify_palylist = np.array([['Pop','Rock','Indie'],[10,15,25],[30,12,17]])
print(spotify_palylist)

#Transpose
Transpose = np.transpose(spotify_palylist)
print(Transpose)

#T
T = spotify_palylist.T
print(T)

[['Pop' 'Rock' 'Indie']
 ['10' '15' '25']
 ['30' '12' '17']]
[['Pop' '10' '30']
 ['Rock' '15' '12']
 ['Indie' '25' '17']]
[['Pop' '10' '30']
 ['Rock' '15' '12']
 ['Indie' '25' '17']]



Given a 1D NumPy array of 15 Flipkart product ratings, use reshape() to convert it into a 3x5 array, then use flatten() to return it to a 1D array. Explain in a comment when you would use flatten() versus ravel() in real projects.

In [ ]:
flipcart_product = np.array([3,5,4,2,3,4,5,1,2,3,5,4,5,2,3]).reshape(3,5)
print(flipcart_product)

a = flipcart_product
a1 = a.flatten()
print(a1)

#Ravel is use when we have to change values in original matrix using conditions.
#flatten is use when we have to convert values to 1D array for calculation.

[[3 5 4 2 3]
 [4 5 1 2 3]
 [5 4 5 2 3]]
[3 5 4 2 3 4 5 1 2 3 5 4 5 2 3]
