In [1]:
import numpy as np

Create a NumPy array called prices with the following values: [199, 299, 399, 499, 599]. Use basic indexing to print the first and last price.

In [4]:
prices = np.array([199,299,399,499,599])

print(prices[0])
print(prices[-1])

199
599


Given a 2D NumPy array representing cricket scores for 3 players across 5 matches, use slicing to extract the scores of all players for matches 2 to 4 (index 1 to 3).

In [10]:
scores = np.array([[150,160,200,156,140],[210,130,189,174,146],[135,202,125,169,153]])
print(scores)
print('Ans:----')
print(scores[:,1:4])

[[150 160 200 156 140]
 [210 130 189 174 146]
 [135 202 125 169 153]]
Ans:----
[[160 200 156]
 [130 189 174]
 [202 125 169]]


You have a NumPy array called ratings = np.array([4.5, 3.8, 4.2, 2.9, 5.0, 3.5]). Use negative indexing to print the last three ratings.

In [11]:
rating = np.array([4.5,3.8,4.2,2.9,5.0,3.5])
print(rating[-3:])

[2.9 5.  3.5]


Create a NumPy array of the first 20 natural numbers. Use step slicing to print every 3rd number starting from the second element.<br><br><em><strong>Hint:</strong> Use the slice notation with a step value.</em>

In [14]:
numbers = np.arange(2,21,3)
print(numbers)

[ 2  5  8 11 14 17 20]


Given a NumPy array of Flipkart product prices, use boolean indexing to extract all prices greater than 500. Print the resulting array.

In [17]:
prices = np.array([600,250,300,700,800,450])

result = (prices>500)
print(result)

[ True False False  True  True False]



You have an array of IPL team scores: np.array([210, 180, 195, 220, 205, 175]). Use np.where() to find the indices of all scores above 200 and print these indices.

In [19]:
scores = np.array([210,180,195,220,205,175])

indices = np.where(scores>200)
print(indices)

(array([0, 3, 4]),)
